version: "3.9"
services:
  webapp:
    image: usmv-app-front-dev-i
    build: 
      dockerfile: docker/Dockerfile.dev
    container_name: usmv-app-front-dev-c
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - "3000:3000"

volumes:
  node_modules: