import Head from "next/head";

const HeadMeta = () => {
  return (
    <Head>
      <meta charSet="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <title>USMV APP</title>
    </Head>
  );
};

export default HeadMeta;
