import * as yup from "yup";

export const userSchema = yup.object({
  lastName: yup.string().required(),
  firstName: yup.string().required(),
  email: yup
    .string()
    .required()
    .test("isComplyingEmail", "L'email saisi n'est pas conforme.", (value, context) =>
      value ? /^[a-z0-9-\-\.]+@[a-z0-9-]+\.[a-z0-9]{2,5}$/.test(value) : true
    ),
  passwordAutoGenerated: yup.boolean(),
  // roles: yup.array(yup.string()).required(),
  gender: yup.string().oneOf(["male", "female"]).notRequired(),
  birthDate: yup.date().notRequired(),
  state: yup.string().oneOf(["pending", "active", "inactive"]).required(),
  validatedAccount: yup.boolean().required(),
});
