import dynamic from 'next/dynamic';
import Head from 'next/head';
import Link from 'next/link';

const LazyComponent = dynamic(() => import("../project/myApp"), {ssr: false})

const Home = () => {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <title>USMV APP</title>
      </Head>
      <LazyComponent />
    </>
  )
}

export default Home
