import Head from 'next/head'
import Image from 'next/image'
import styles from '../sass/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>USMV APP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
    </div>
  )
}
